name: Retrieve Key Vault Secret

on:
  push:
    branches:
      - main

jobs:
  fetch-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CREDENTIAL1 }}

      - name: Retrieve Secret from Key Vault
        id: get-secret
        run: |
          SECRET_VALUE=$(az keyvault secret show --name servicebus --vault-name vault1019 --query value -o tsv)
          echo $SECRET_VALUE > secret-value.txt

      - name: Create Kubernetes Secret
        run: |
          kubectl create secret generic order-queue-secret \
            --from-literal=ORDER_QUEUE_PASSWORD=$(cat secret-value.txt) \
            --namespace=default --dry-run=client -o yaml > secret.yaml
          kubectl apply -f secret.yaml

      - name: Deploy Kubernetes Resources
        run: |
          kubectl apply -f k8s/deployment.yaml
