name: Docker compose and push to ACR
on:
  push:
    branches:
      - main
  #  path:
  #    - 'docker-compose-quickstart.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CREDENTIAL1 }}

      # Docker Login to ACR
      - name: Docker Login to ACR
        run: |
          az acr login --name ${{ vars.REGISTRY_NAME }}

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker compose -f docker-compose-quickstart.yml up -d

        
      # See Docker images
      - name: See Docker Image
        run: |
          docker images

       # See image running
      - name: See Running Docker Image
        run: |
          docker ps



      - name: Push front
        run: |
          docker tag aks-full-stack-architecture-store-front acr777aditya.azurecr.io/aks-store-demo-store-front 
          docker push acr777aditya.azurecr.io/aks-store-demo-store-front

      
      - name: Push product-service
        run: |
          docker tag aks-full-stack-architecture-product-service acr777aditya.azurecr.io/aks-store-demo-product-service
          docker push acr777aditya.azurecr.io/aks-store-demo-product-service

          
      
      - name: Push order-service
        run: |
          docker tag aks-full-stack-architecture-order-service acr777aditya.azurecr.io/aks-store-demo-order-service
          docker push acr777aditya.azurecr.io/aks-store-demo-order-service

      #- name: Push virtual-worker
       # run: |
        #  docker tag aks-store-demo-virtual-worker acr777aditya.azurecr.io/aks-store-demo-virtual-worker
         # docker push acr777aditya.azurecr.io/aks-store-demo-virtual-worker



      #- name: Push virtual-customer
       # run: |
        #  docker tag aks-store-demo-virtual-customer acr777aditya.azurecr.io/aks-store-demo-virtual-customer
         # docker push acr777aditya.azurecr.io/aks-store-demo-virtual-customer





     # - name: Push makeline-service
     #   run: |
     #     docker tag aks-store-demo-makeline-service acr777aditya.azurecr.io/aks-store-demo-makeline-service
     #     docker push acr777aditya.azurecr.io/aks-store-demo-makeline-service





      - name: Push RABBITMQ
        run: |
          docker tag rabbitmq:3.13.2-management-alpine acr777aditya.azurecr.io/rabbitmq:3.13.2-management-alpine
          docker push acr777aditya.azurecr.io/rabbitmq:3.13.2-management-alpine





     # - name: Push Mongo
     #   run: |
      #        docker tag mongo:6.0.6 acr777aditya.azurecr.io/mongo:6.0.6
       #       docker push acr777aditya.azurecr.io/mongo:6.0.6



     # - name: Push store-admin
     #   run: |
       #      docker tag aks-store-demo-store-admin acr777aditya.azurecr.io/aks-store-demo-store-admin
       #      docker push acr777aditya.azurecr.io/aks-store-demo-store-admin


    
